{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.3.0.aar",
          "url": "lifecycle-viewmodel-2.3.0.aar",
          "size": 11144,
          "sha512": "50d6608da645e507009cdb0fe73f4e1493eebfd7f32d29bd10e155e7fc72351d05d6f924807245d5e41a83511e5e931c6b4b1d20e748c8f0b782a432c67c5a54",
          "sha256": "cea8f26fa232037922b69af9cd1bde2df1211acc8b75253e425b7150a5fca59d",
          "sha1": "5ab6b6962fb017b013e0e716d4a1e3e1cc7d3857",
          "md5": "d8fc2d15115221cd60931f01d9275b29"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.3.0.aar",
          "url": "lifecycle-viewmodel-2.3.0.aar",
          "size": 11144,
          "sha512": "50d6608da645e507009cdb0fe73f4e1493eebfd7f32d29bd10e155e7fc72351d05d6f924807245d5e41a83511e5e931c6b4b1d20e748c8f0b782a432c67c5a54",
          "sha256": "cea8f26fa232037922b69af9cd1bde2df1211acc8b75253e425b7150a5fca59d",
          "sha1": "5ab6b6962fb017b013e0e716d4a1e3e1cc7d3857",
          "md5": "d8fc2d15115221cd60931f01d9275b29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-2.3.0-sources.jar",
          "url": "lifecycle-viewmodel-2.3.0-sources.jar",
          "size": 11018,
          "sha512": "01e681c96df3864f3e27e6a5436688b25439cb113177de78d9be4e4f0bbf17169d66bf722969a91d63769d1571c0d2fbae615410babbfe0856f5f0a36c2c12ee",
          "sha256": "a903de30a219922f96aba02883e36ebd6b009cf9b803342b0fd8d3b390c0982c",
          "sha1": "055d6fa3541ca02167b0bd62a16fbdaec2a71622",
          "md5": "2e53aa805482f532a082477e19664b78"
        }
      ]
    }
  ]
}
