{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler",
    "version": "4.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zz53gouv6nfztoi24j3d3xklai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.2.jar",
          "url": "databinding-compiler-4.2.2.jar",
          "size": 1175252,
          "sha512": "e98da1b6511d80a02d829dfdc6f8d27e12d286d685b593d78c2c15ccc1d47a7d4071775a7182da7d01c3c73cfc97c7be6fa81b9c74f1b53465471a9d24d1f29a",
          "sha256": "34752a8623408c7c61a1d4a07bb1ac267b76fcbb79e4c24f116851256098c1e7",
          "sha1": "cec2ea3966520f89e7728bab98430d3097dbc4d6",
          "md5": "9f0fcecdc5dc2c5d06567b0d10413a19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-4.2.2.jar",
          "url": "databinding-compiler-4.2.2.jar",
          "size": 1175252,
          "sha512": "e98da1b6511d80a02d829dfdc6f8d27e12d286d685b593d78c2c15ccc1d47a7d4071775a7182da7d01c3c73cfc97c7be6fa81b9c74f1b53465471a9d24d1f29a",
          "sha256": "34752a8623408c7c61a1d4a07bb1ac267b76fcbb79e4c24f116851256098c1e7",
          "sha1": "cec2ea3966520f89e7728bab98430d3097dbc4d6",
          "md5": "9f0fcecdc5dc2c5d06567b0d10413a19"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.2-javadoc.jar",
          "url": "databinding-compiler-4.2.2-javadoc.jar",
          "size": 351897,
          "sha512": "dd815003ba24bbcd78b40ff8814d330d1d357599aad44a2296707d3e51b6b54de15568fe0927c8df67e4a42510c88b9a49d958065bf2fd6ec122aaa62760692b",
          "sha256": "ea9404d679bb0bec4bda909df9fa787d1d10b209ebdb0c4b04f59800739b0e7c",
          "sha1": "018d19da6cc3ab785fca3cf3d6f51a513bc83a60",
          "md5": "fdf9f4a79353a4dc2ef7d8848a93111b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-4.2.2-sources.jar",
          "url": "databinding-compiler-4.2.2-sources.jar",
          "size": 564713,
          "sha512": "f8f2c0ae14d267424890d87d2ad1446ccf9529490bf18730210dfb92b72285b47c374b668ee51bf4af2c28b47e625bdb3284cb019db5570fed90e0fcb0cde0b0",
          "sha256": "084853b0f83d0358bf6ab96c88716533ab2f5447c6da2606ecdbe9acbed9496d",
          "sha1": "e5faa42382924bcefb6b4ed5893786389ec89724",
          "md5": "459bc739c84a1abd4b19bfeec49d3a19"
        }
      ]
    }
  ]
}
