{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.permissions-dispatcher",
    "module": "permissionsdispatcher-processor",
    "version": "4.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rlmposmaufcovnoazkk5234a7q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "permissionsdispatcher-processor-4.9.2.jar",
          "url": "permissionsdispatcher-processor-4.9.2.jar",
          "size": 94509,
          "sha512": "95a1ae76878ab373793c5fa59e001eb83ed3df4845de58ff4bf689b6395564906271d737b5f2cbf1056cbd05e4c221b9718528402924ca8c662fce471731a7bf",
          "sha256": "8bd07178611cffe439707be013ceaf2f9944bfe2ac5f285af112022b830c4c74",
          "sha1": "d6cc764d8cd0c6e4b8e8702ab1cf623bb22d2bdf",
          "md5": "c60c5b0d43ca393fd8616231ac0568b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.permissions-dispatcher",
          "module": "permissionsdispatcher-annotation",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "permissionsdispatcher-processor-4.9.2.jar",
          "url": "permissionsdispatcher-processor-4.9.2.jar",
          "size": 94509,
          "sha512": "95a1ae76878ab373793c5fa59e001eb83ed3df4845de58ff4bf689b6395564906271d737b5f2cbf1056cbd05e4c221b9718528402924ca8c662fce471731a7bf",
          "sha256": "8bd07178611cffe439707be013ceaf2f9944bfe2ac5f285af112022b830c4c74",
          "sha1": "d6cc764d8cd0c6e4b8e8702ab1cf623bb22d2bdf",
          "md5": "c60c5b0d43ca393fd8616231ac0568b6"
        }
      ]
    }
  ]
}
